=== AngieMiv/markup-language-1DAW/XML/XSD/xsd_aresolver.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- DefiniciÃ³n de elemento persona con tipo complejo -->
  <xs:element name="persona">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="edad" type="xs:int" minOccurs="1" maxOccurs="1"/>
        
        <xs:element name="direccion">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="calle" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="ciudad" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="codigoPostal" type="xs:string" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="contactos">
          <xs:complexType>
            <xs:all>
              <xs:element name="email" type="xs:string" minOccurs="0" maxOccurs="1"/>
              <xs:element name="telefono" type="xs:string" minOccurs="0" maxOccurs="1"/>
            </xs:all>
          </xs:complexType>
        </xs:element>

        <xs:element name="informacion">
          <xs:complexType>
            <xs:choice>
              <xs:element name="empleo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="puesto" type="xs:string"/>
                    <xs:element name="empresa" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="estudios">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nivel" type="xs:string"/>
                    <xs:element name="universidad" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:choice>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== AngieMiv/markup-language-1DAW/XML/XSD/xsd_XML_aresolver.xml
<?xml version="1.0" encoding="UTF-8"?>
<persona xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd_aresolver.xsd">
  <nombre>Nickolas Magallanes</nombre>
  <edad>20</edad>
  <direccion>
    <calle>Extremadura</calle>
    <ciudad>Toledo</ciudad>
    <codigoPostal>45513</codigoPostal>
  </direccion>
  <contactos>
    <email>nick3m9220@gmail.com</email>
    <telefono>600548345</telefono>
  </contactos>
  <informacion>
    <empleo>
        <puesto>Programador</puesto>
        <empresa>Stark Enterprises</empresa>
    </empleo>
  </informacion>
</persona>
