=== AngieMiv/markup-language-1DAW/XML/XSD/xsd_aresolver_conatributos.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Elemento global único (raíz) -->
  <xs:element name="persona">
    <xs:complexType>
      <xs:sequence>
        <!-- Elementos secuenciales -->
        <xs:element name="nombre" type="xs:string" />
        <xs:element name="apellido" type="xs:string" />
        <xs:element name="edad" type="xs:int" />
        <xs:element name="telefono" type="xs:string" />
        <!-- Uso de xs:choice -->
        <xs:element name="vehiculo">
          <xs:complexType>
              <xs:choice>
                <xs:element name="coche" type="xs:string" />
                <xs:element name="moto" type="xs:string" />
                <xs:element name="bicicleta" type="xs:string" />
              </xs:choice>
            <!-- Atributo con valor fijo -->
            <xs:attribute name="color" type="xs:string" fixed="rojo" />
          </xs:complexType>
        </xs:element>
        <!-- Uso de xs:all -->
        <xs:element name="direccion">
          <xs:complexType>
            <xs:all>
              <xs:element name="calle" type="xs:string" />
              <xs:element name="numero" type="xs:int" />
              <xs:element name="codigoPostal" type="xs:string" />
            </xs:all>
            <!-- Atributo opcional -->
            <xs:attribute name="tipo" type="xs:string" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <!-- Atributo obligatorio con valor predeterminado -->
      <xs:attribute name="pais" type="xs:string" default="España" />
      <!-- Atributo obligatorio -->
      <xs:attribute name="sexo" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== AngieMiv/markup-language-1DAW/XML/XSD/xsd_XML_aresolver_conatributos.xml
<?xml version="1.0" encoding="UTF-8"?>
<persona sexo="Masculino" pais="EspaÃ±a" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd_aresolver_conatributos.xsd">
    <nombre>Nick</nombre>
    <apellido>Magallanes</apellido>
    <edad>20</edad>
    <telefono>600548345</telefono>
    <vehiculo color="rojo">
        <coche>Terreneitor 3000</coche>
    </vehiculo>
    <direccion tipo="Piso">
        <calle>Extremadura</calle>
        <numero>21</numero>
        <codigoPostal>45513</codigoPostal>    
    </direccion>
</persona>
