<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Viajes [
	<!ELEMENT Viajes (viaje, info-html, info-css)>
	<!ELEMENT viaje (viajeros, detalles_viaje)>
		<!ELEMENT viajeros (viajero+)> <!-- con el "+" indicamos que pueden haber 1 o más ocurrencias-->
			<!ELEMENT viajero (nombre_cliente*, apellidos_cliente)> <!--con el "*" indicamos que puede haber 0 o más ocurrencias-->
				<!ATTLIST viajero id CDATA #REQUIRED> <!-- definimos un atributo a un elemento-->
				<!ELEMENT nombre_cliente (#PCDATA)>
				<!ELEMENT apellidos_cliente (#PCDATA)>
		<!ELEMENT detalles_viaje (fecha_inicio, fecha_fin, origen, precio, destinos_viaje)>
			<!ELEMENT fecha_inicio (#PCDATA)>
			<!ELEMENT fecha_fin (#PCDATA)>
			<!ELEMENT origen (#PCDATA)>
			<!ELEMENT precio (#PCDATA)>
			<!ELEMENT destinos_viaje (ciudad, hotel, num_noches)+>
				<!ELEMENT ciudad (#PCDATA)>
					<!ATTLIST ciudad destino CDATA #REQUIRED>
				<!ELEMENT hotel (#PCDATA)>
					<!ATTLIST hotel destino CDATA #REQUIRED>
				<!ELEMENT num_noches (#PCDATA)>
					<!ATTLIST num_noches destino CDATA #REQUIRED>
	<!ELEMENT info-html ANY>
	<!ELEMENT info-css ANY>
]>
<Viajes>
	<viaje>
		<viajeros>
			<viajero id="1">
				<nombre_cliente>Alba</nombre_cliente>
				<apellidos_cliente>Martinez González</apellidos_cliente>
			</viajero>
			<viajero id="2">
				<nombre_cliente>Óscar Andre</nombre_cliente>
				<apellidos_cliente>Cebrián</apellidos_cliente>
			</viajero>
		</viajeros>
		<detalles_viaje>
			<fecha_inicio>2025-01-11</fecha_inicio>
			<fecha_fin>2025-02-11</fecha_fin>
			<origen>Madrid, España</origen>
			<precio>5000$</precio>
			<destinos_viaje>
				<ciudad destino="1">Nara, Japón</ciudad>
				<hotel destino="1">Deer hostel</hotel>
				<num_noches destino="1">15</num_noches>
				<ciudad destino="2">Torsken, Noruega</ciudad>
				<hotel destino="2">Torsken Brygge</hotel>
				<num_noches destino="2">15</num_noches>
			</destinos_viaje>
		</detalles_viaje>
	</viaje>
	<info-html>
		<![CDATA[
			<DOCTYPE! html>
			<html>
			<head>
				<link rel="stylesheet" href="./style.css>
			</head>
			<body>
				<h1>Hello World</h1>
			</body>
			</html>
		]]>
	</info-html>
	<info-css>
	<![CDATA[
		body {
			background-color: blue;
		}
	]]>
	</info-css>
</Viajes>